Add pathlib support
parafoxia/len8 pull request #12
Opened 2021-11-04 22:47 UTC by parafoxia

### Summary
This PR modifies the API to utilise the power of `pathlib`. It also fixes some typehinting errors Pyright didn't pick up. There's a new Mypy test within the noxfile, though the Pyright one has been retained.

### Tasks
- [x] I have searched for similar/duplicate PR's, and there are none.
- [x] I have made tests to validate any changes to the code base.
- [x] I have run `nox` and all sessions pass.

### Related issues
Closes #6.

2021-11-04 23:08 UTC, parafoxia commented
Do we think this should be released as v0.3.2 or v0.4.0? Part of me is leaning to the latter cos there's a lot of changes, but another part toward the former because all the changes are in the backend, and there aren't really any "new" features.

2021-11-05 16:37 UTC, Jonxslays commented
> Do we think this should be released as v0.3.2 or v0.4.0? Part of me is leaning to the latter cos there's a lot of changes, but another part toward the former because all the changes are in the backend, and there aren't really any "new" features.

According to [SemVer](https://semver.org/) we would be ok with either option, if you feel 0.4 is warranted lets go with that.

> Minor version Y (x.Y.z | x > 0) MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes.

2021-11-05 16:38 UTC, Jonxslays commented
But to be fair, we still haven't released 1.0 so I don't think its too relevant right now.

2021-11-05 17:12 UTC, Jonxslays requested changes
Just a couple of things here.

2021-11-05 17:12 UTC, Jonxslays commented on len8/models/checker.py
> +        return True
This change does not take into account someone passing an absolute path to the file they want to exclude. 

Assume every file has lines that are too long for minimal reproduction:

Directory structure
```bash
.
├── ignore_me
│   ├── test2.py
│   └── test.py
└── test.py
```

When using a relative path, `./test.py` is ignored as expected.
```bash
$ len8 . -x test.py
2 line(s) are too long:
- /home/jon/repro/ignore_me/test.py, line 1 (119/79)
- /home/jon/repro/ignore_me/test2.py, line 1 (119/79)
```

When using an absolute path for the exclude, `test.py` is not ignored.
```bash
$ len8 . -x $(pwd)/test.py
3 line(s) are too long:
- /home/jon/repro/test.py, line 1 (119/79)
- /home/jon/repro/ignore_me/test.py, line 1 (119/79)
- /home/jon/repro/ignore_me/test2.py, line 1 (119/79)

$ echo $(pwd)/test.py
/home/jon/repro/test.py
```

2021-11-05 19:54 UTC, Jonxslays approved these changes
amazing, you cleaned it up a lot.

2021-11-05 20:00 UTC, merged